services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: auth_db

    ports:
      - "5433:5432"

    volumes:
      - auth_data:/var/lib/postgresql/data

  user-db:
    image: postgres:16
    container_name: user-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_db

    ports:
      - "5434:5432"

    volumes:
      - user_data:/var/lib/postgresql/data

  product-db:
    image: postgres:16
    container_name: product-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: product_db

    ports:
      - "5435:5432"

    volumes:
      - product_data:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: order-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: order_db

    ports:
      - "5436:5432"

    volumes:
      - order_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service

    container_name: auth-service

    restart: unless-stopped

    ports:
      - "3001:3001"

    depends_on:
      - auth-db

  user-service:
    build:
      context: ./user-service

    container_name: user-service

    restart: unless-stopped

    ports:
      - "3002:3002"

    depends_on:
      - user-db

  product-service:
    build:
      context: ./product-service

    container_name: product-service

    restart: unless-stopped

    ports:
      - "3003:3003"

    depends_on:
      - product-db

  order-service:
    build:
      context: ./order-service

    container_name: order-service

    restart: unless-stopped

    ports:
      - "3004:3004"

    depends_on:
      - order-db

  notification-service:
    build:
      context: ./notification-service

    container_name: notification-service

    ports:
      - "3005:3005"

    depends_on:
      - rabbitmq

  gateway:
    build:
      context: ./gateway

    container_name: gateway

    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - auth-service
      - user-service
      - product-service
      - order-service

  rabbitmq:
    image: rabbitmq:3-management

    container_name: rabbitmq

    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  auth_data:
  user_data:
  product_data:
  order_data:
